name: Report Elixir Coverage

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  report-coverage:
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - run: mkdir -p ${{ runner.temp }}/cover
      - run: echo Fetching artifacts for ${{ github.event.workflow_run.id }}, event name ${{ github.event_name }}, triggered by ${{ github.event.workflow_run.event }}
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: elixir-lcov
          path: ${{ runner.temp }}/cover/elixir-lcov.zip
      - working-directory: ${{ runner.temp }}/cover
        run: |
          unzip elixir-lcov.zip
          echo "PR_SHA=$(cat PR_SHA)" >> $GITHUB_ENV
          echo "PR_NUMBER=$(cat PR_NUMBER)" >> $GITHUB_ENV
      - uses: actions/checkout@v2 # UNTRUSTED CODE - do not run scripts from it
        with:
          ref: ${{ env.PR_SHA }}
      - name: Upload coverage artifact and post comment
        uses: mbta/github-actions-report-lcov@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-files: ${{ runner.temp }}/cover/lcov*.info
          artifact-name: elixir-code-coverage
